### ISSUE TITLE
Center other elements of taskbar.

### ISSUE THREAD

**Issue by x7airworker** [mdhiggins/CenterTaskbar#11]
Is it possible to also center the windows icon and/or the date widget?
Then it would be very cool to also make the Taskbar transparent.

**Comment by mdhiggins** [comment]
Not currently possible. The start and time positioning might be doable though don’t know where the start menu would appear but I’m not actively developing this project for new features. You’re welcome to submit a pull request if you’d like this.

I believe there are other tools that do transparency but it’s nothing something the current UIAutomation implementation currently supports.
