### ISSUE TITLE
Possible speed in Reboot?

### ISSUE THREAD

**Issue by massimilianobaldo** [mdhiggins/CenterTaskbar#12]
I tried to set the executible files as a start up file, but i have to wait 1 minute before the application starts. 
Is possible to do something about? Maybe using the process of windows?

**Comment by mdhiggins** [comment]
The app has a 'start with windows' option when you right click the icon in the tool tray that adds the program to  the startup registry

There is some delay and that will be highly dependent on how much other stuff is starting with your computer and how slow your computer is. Mine takes a few seconds to start
