### ISSUE TITLE
Sometimes gets stuck

### ISSUE THREAD

**Issue by itisrazza** [mdhiggins/CenterTaskbar#14]
The taskbar sometimes doesn't move when new applications open and close. It doesn't just not work like in #8, but it's inconsistent. 

I cannot consistently recreate the issue, but it's subtly jarring when it happens. I'll add more info as I have more time to work on it.

**Comment by mdhiggins** [comment]
Likely due to some apps not triggering the UIAutomation events like they are supposed to. I haven't been able to find a better event to monitor that's more inclusive but open to suggestions
