### ISSUE TITLE
Microsoft To-Do cannot be stared from taskbar while CenterTaskbar is running

### ISSUE THREAD

**Issue by Utopikachu** [mdhiggins/CenterTaskbar#15]
Microsoft To-Do cannot be stared from taskbar while CenterTaskbar is running.

**Comment by mdhiggins** [comment]
Works fine for me
There should be no reason a specific app can't be launched that's not how the program works

**Comment by mdhiggins** [comment]
I can look into this more if you provide some more info or specifics about what's going on but I'm unable to reproduce this. I assume you mean start but I don't use To-Do so not sure if staring tasks is a feature or something I'm unaware of
