### ISSUE TITLE
Toolbars are not positioned correctly

### ISSUE THREAD

**Issue by amrbashir** [mdhiggins/CenterTaskbar#20]
**Describe the bug**
Toolbars are not positioned correctly 

**Screenshots**
![image](https://user-images.githubusercontent.com/48618675/97208445-cff60300-17c3-11eb-9bb2-4618cce66c20.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10 version 2004
 - Version [e.g. 22] 1.5

**Additional context**
The toolbar used is: NetSpeedMonitor and I have TranslucentTB running to make the taskbar transparent.

**Comment by mdhiggins** [comment]
Those toolbars are not part of the normal UI stack and not part of the button grouping that is centered and cannot be repositioned

**Comment by amrbashir** [comment]
[TaskbarX](https://github.com/ChrisAnd1998/TaskbarX) which is a similar tool written in VisualBasic, had this issue a while ago and They managed to fix it.
I would be glad to help but my understanding of TaskbarX code base is not good at all and I don't even know VisualBasic.
I moved from TaskbarX to your app because your app is simple and not bloated. Good job man. 
If I ever find a solution I will make sure to submit a PR.
