### ISSUE TITLE
Is it possible to make it automatically re-centre the task bar when explorer.exe is reset?

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [mdhiggins/CenterTaskbar#23]
If you restart explorer.exe, all the task bar icons will situate itself on the left according to Window's default behaviour. To fix this, you have to manually click the scan for screens button. This is fairly inconvenient when you are regularly restarting explorer.exe. Would it possible to automate this?

**Comment by mdhiggins** [comment]
You officially win the award for most nonsense workflow after this and your last request. 

Not any easy way to do this without adding lots of overhead and possible background performance.

Might I suggest making a batch file that restarts both explorer and the centertaskbar program and then when you restart explorer it will just do both?

Also why are you regularly restarting explorer?

```
@echo off
taskkill /f /im explorer.exe >nul
taskkill /f /im centertaskbar.exe >nul
start explorer.exe
start centertaskbar.exe
```

Will need to put the full path to centertaskbar

**Comment by noudadrichem** [comment]
I got a cron job running every 10 seconds to restart my explorer.exe to prevent memory leaks, so is it nonsense if it works?
Having 0 issues with CenterTaskBar. I also put some butter on my montherboard to make CenterTaskBar run smoother, it works for the centering animation! Also found out CenterTaskBar is using little to no RAM but downloaded some more anyway.

**Comment by mdhiggins** [comment]
Good old motherboard butter. Solution to all problems

**Comment by noudadrichem** [comment]
Thanks for making this add-on and keeping it up to date this well! @mdhiggins

**Comment by asdsadsaasd12312132** [comment]
> Also why are you regularly restarting explorer?

I was performing tweaks to my registry and needed to restart explorer to see the effect. I wouldn't complain if it was just a few times but I was spending a lot of time tweaking and was restarting explorer every minute or so for a few days. Anyway, I am done now, so it's not really a big deal. Feel free to close the issue if desired.
