### ISSUE TITLE
Problem when pressing shift keys

### ISSUE THREAD

**Issue by afrey15** [mdhiggins/CenterTaskbar#24]
When you press either shift key, all taskbar icons forget their position and return to the far left of the taskbar for a brief moment. Is this possible to fix?

**Comment by mdhiggins** [comment]
Do you have some custom toolbar or tool tray icon installed that is responding to shift key presses? Those are likely changing and triggering a redraw which I can't fix. Best bet is to try and disable those things

**Comment by afrey15** [comment]
I've got Windows Centering Helper installed that responds to 3 shift clicks. That must be it. Thanks for the response.
