### ISSUE TITLE
CENTERTASKBAR

### ISSUE THREAD

**Issue by AKmobpsycho** [mdhiggins/CenterTaskbar#25]
how do i install it?

**Comment by mdhiggins** [comment]
You just run the executable. Right click on the tool tray to add it to startup.

**Comment by AustinGraphics** [comment]
I have opened up the file and there is no executable anywhere!

**Comment by mdhiggins** [comment]
Its under releases

**Comment by AustinGraphics** [comment]
It worked, thanks!
