### ISSUE TITLE
Icons un-center when an app (dis)appears in the notification area

### ISSUE THREAD

**Issue by DanielEgner** [mdhiggins/CenterTaskbar#28]
**To Reproduce**
1. Start an application which adds an icon to the notification area (aka system tray), for example OBS Studio. The same happens if an app which has an icon in the notification area is closed.
2. All icons pinned to taskbar move to the left. Most of the time they move back to Windows' default position (next to the Start Menu button), sometimes they are out of center with an offset to the left.
3. A manual re-scan helps to center the icons.

**Expected behavior**
Optimal behavior: Application icons remain in center.
Minimum behavior: (Dis)appearing items in the notification area trigger a re-scan so that application icons re-center without any manual user action.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2
 - Version 1.92

**Comment by DanielEgner** [comment]
I wanted to add some screenshots. Tried to reproduce the effect on another machine.
Edition Windows 10 Enterprise, Version	20H2, OS build 19042.928, Windows Feature Experience Pack 120.2212.551.0
CenterTaskbar behaved normal. Maybe it is only with certain applications or on a particular OS version. I will test further later today.

**Comment by DanielEgner** [comment]
Performed several other tests on the computer where I detected the issue. All fine now, no misalignment. Maybe there was an interference with some background activity that I was not aware of. I will try to monitor that. For the time being I will close this issue.

**Comment by DanielEgner** [comment]
Today the issue happened again.

![image](https://user-images.githubusercontent.com/82779660/115525818-becc1180-a28f-11eb-807e-e31c1fcc0bae.png)

As soon as I open for example the task manager and it shows its blue icon in the notification area

![image](https://user-images.githubusercontent.com/82779660/115525956-dc00e000-a28f-11eb-9a8a-99cd17496da6.png)

the icons on the taskbar move to the left.

![image](https://user-images.githubusercontent.com/82779660/115526040-ede28300-a28f-11eb-811f-d050dcda4a5c.png)

When I re-scan

![image](https://user-images.githubusercontent.com/82779660/115525223-2e8dcc80-a28f-11eb-87d8-c546d027dd90.png)

they are centered again.

![image](https://user-images.githubusercontent.com/82779660/115526113-fd61cc00-a28f-11eb-834a-76401b49a515.png)

If I close task manager

![image](https://user-images.githubusercontent.com/82779660/115526249-1ff3e500-a290-11eb-9d8a-fc026f2068d2.png)

the icons move again to the left.

![image](https://user-images.githubusercontent.com/82779660/115526600-7e20c800-a290-11eb-825f-97ca2ea7e13c.png)

This happens not only with task manager, but I showed it with this app to make it easier to reproduce the effect since this app is available on every Windows machine.

**Comment by mdhiggins** [comment]
The redraw is something that can't be fixed, its just a limitation with how the app manipulates the position. When a new icon is added to the tooltray windows redraws all the parent containers and this causes that brief reset, though in my testing the position quickly corrects back to center as it should. I'm running 19041 right now though so maybe this is a new issue. I'll have to update and see and then if its persistent try and figure out a way to then trigger a rescan if that's the case

**Comment by DanielEgner** [comment]
The weird and frustrating thing is that this issue does not always kick in. That makes it hard to reproduce the effect. The same scenario that I described before works at the moment absolutely without any flaws. I try my best to narrow down the possible side effects from other programs to find out, under which circumstances the re-center works and when it does not. If you have a debug-version that logs events etc to help with the issue I would be okay to run that and provide additional information if that helps.

**Comment by DanielEgner** [comment]
BTW I noticed the other day that sometimes the icons don't move entirely to the left but instead they are out of center with some offset to the left. Did you ever consider to implement a global hotkey (configurable) where a user could trigger the re-scan? Would be more convenient than to right-click the icon, select "Scan for screens" and click that.

**Comment by mdhiggins** [comment]
Have a new build using .Net 5.0 that includes additional events

The one relevant to you is
`Automation.AddStructureChangedEventHandler(trayWnd, TreeScope.Element | TreeScope.Descendants | TreeScope.Children, _structChangeHandler);`

This should capture situations where the parent taskbar is redrawn and hopefully kick off a cycle of centering

https://github.com/mdhiggins/CenterTaskbar/actions/runs/858072723

Build can be downloaded there

**Comment by DanielEgner** [comment]
Downloaded this release and will give it a try during the coming days. Feedback will follow for sure.

**Comment by mdhiggins** [comment]
Just following up on this, any improvement?

**Comment by DanielEgner** [comment]
Even with the former version I almost thought the issue had disappeared "by magic", but then I had another of those rare misalignments. During the last 8 days I used the .Net 5.0 based release and it seemed fine but the issue is not 100'% solved. During my test phase it happened to me on two different computers that the icons suddenly moved to the left and stayed there. I had to close CenterTaskbar and restart to force the correct alignment. Then I could not reproduce the effect. I understand that this makes debugging almost impossible for you. I would not mind if you close the issue and flag it "not reproducable". No other user chimes in so maybe it is not worth it to spend your time.

**Comment by mdhiggins** [comment]
Thanks for following up, I guess we'll close this for now but if I find another more definitive means of triggering the rescan/refresh I will certainly let you know and try and implement things

I'm hoping at some point this will just be integrated in a future windows build for a cleaner solution
