### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by iHaired** [mdhiggins/CenterTaskbar#3]
Hi.
First of all — love this app! A must have for all ultrawide monitor owners.
Is there any way to set refresh rate without cmd so it stays after OS restart?

**Comment by mdhiggins** [comment]
When you check the "Start with Windows" option from the task tray it includes the current refresh rate in the startup registry key so it will resume back at whichever rate after restart

**Comment by iHaired** [comment]
Thanks!
