### ISSUE TITLE
Can I launch it without launching Visual Studio as a lightweight program?

### ISSUE THREAD

**Issue by ledserapteur** [mdhiggins/CenterTaskbar#33]
This is a great program, but I have difficulties running Visual Studio each time I need to launch this program, and it is kind of not easy and klunky (VS eats 500mb RAM). Can I run this beautiful piece of code as an exe file?

**Comment by mdhiggins** [comment]
Oof, I'm impressed you managed to get to the point where you could get VS installed and get the app to compile without realizing that's how you build your own EXE file, you don't need to run it through studio

Also, the EXE is posted on Github and has been for years

The latest build is always attached as an automated creation on the Github Actions, here's the most recent
https://github.com/mdhiggins/CenterTaskbar/suites/2887646858/artifacts/64635694

And more incremental but less frequent builds are under 'Releases'
https://github.com/mdhiggins/CenterTaskbar/releases

<300kb
