### ISSUE TITLE
Any plan to support for Windows 11?

### ISSUE THREAD

**Issue by quangtrang1111** [mdhiggins/CenterTaskbar#36]
Now windows 11 only have 2 option to set the start menu and the icons in center or left.
I think it would be awesome it we set the start menu in left and the app icon in the center.
What do you think?

Thanks.

**Comment by mdhiggins** [comment]
The new windows taskbar implementation in 11 breaks the methods used in windows 10 to center the taskbar so this won't be possible and compatibility will end on windows 10. Best bet is to petition Microsoft to give an option to have the start button remain in the left corner
