### ISSUE TITLE
It doesn't work on Windows11.

### ISSUE THREAD

**Issue by F-Unction** [mdhiggins/CenterTaskbar#37]
**Describe the bug**
It doesn't work on Windows11.

**To Reproduce**
1. Upgrade to Windows11
1. Open the software.
2. And find it doesn't work.

**Expected behavior**
It works as it was on Windows 10.

**Screenshots**
![Snipaste_2021-10-05_12-51-26](https://user-images.githubusercontent.com/51352133/135962103-d6044808-674f-4286-b763-e1433871e945.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: latest

**Additional context**
I know that windows 11 has provided central taskbar.
But the start icon is also moved to the center, that's not good.

**Comment by mdhiggins** [comment]
Windows 11 will not be supported. See previous issues regarding this. The start button and icons are merged under the same UI group now and cannot be separated using the UIAutomation techniques this program utilizes. Sorry

**Comment by F-Unction** [comment]
Thank you.
And for @microsoft, fuck you.

**Comment by mdhiggins** [comment]
Yeah it's a shame and they could easily make it an option with much cleaner native animations than these programs but instead they removed all kinds of functionality
